Set up docker-compose.
m-danya/public-habit-tracker pull request #2
Opened 2023-05-15 21:28 UTC by kobrineli

2023-05-20 13:35 UTC, m-danya requested changes

2023-05-20 13:35 UTC, m-danya commented on Dockerfile
> +    apt -y install python3.10 pip && pip install poetry
https://python-poetry.org/docs/

наверное лучше ставить черзе bash скрипт, чтоб потом не было приколов

2023-05-20 13:35 UTC, m-danya commented on Dockerfile
> +FROM ubuntu:20.04
[Говорят](https://stackoverflow.com/questions/47047520/python-base-image-vs-ubuntu-base-image-installing-python-separately-in-docker), что лучше использовать специализированный образ. Думаю нам лучше взять python3.10-slim, чтоб там ничего лишнего не было (+ тогда не надо ниже ставить питон и пип)

https://snyk.io/blog/best-practices-containerizing-python-docker/
https://hub.docker.com/_/python
https://medium.com/swlh/alpine-slim-stretch-buster-jessie-bullseye-bookworm-what-are-the-differences-in-docker-62171ed4531d

2023-05-20 13:35 UTC, m-danya commented on Dockerfile
> +CMD poetry env use python3.10 && poetry run python3 src/main.py
очень весёлый трюк с bind mount, конечно, но лучше давай через COPY))
(обсудили)

2023-05-20 13:35 UTC, m-danya commented on README.md
> +There is an almost ready file called `.env.example` for running via Docker,
`via Docker` -> `the bot`
и `locally` ниже в аналогичном месте тож

2023-05-20 13:35 UTC, m-danya commented on docker-compose.yml
> +        depends_on: [pht-db, pht-redis]
ого какой синтаксис, первый раз вижу (видел раньше только через дефисы перечисление как и везде), прикол

2023-05-20 13:35 UTC, m-danya commented on README.md
>  ### Locally
можно дописать `(useful for development)`, типа что дебаггер можно юзать без прокидывания внутрь докера всяких штук

2023-05-21 09:58 UTC, m-danya commented on docker-compose.yml
> +        image: postgres:latest
этот образ автоматически создает volume (можно посмотреть так: `docker inspect pht-db`, там будет `Mounts`), тут всё отлично работает.

а редис не создаёт. поэтому у редиса данные при перезапуске слетают данные

но тут вообще я думаю, стоит ли нам вообще редис использовать для персистентного хранения джобов.

**Если хранить**, то при перезапуске бота в продакшне он увидит, что некоторые джобы он должен был сделать, пока шёл деплой. Это хорошо. Но тогда надо правильно настроить параметры у редиса, чтобы 
**Если не хранить**, то это минус лишний инструмент. Можно просто при запуске бота для всех юзеров делать `set_up_scheduler_job` и всё, хранится они могут спокойно в оперативке просто (как по дефолту и происходит)

2023-05-21 10:55 UTC, m-danya commented
Всё, с редисом разобрался, всё работает (вроде норм что я заюзал `--protected-mode "no"`, т.к. у нас redis доступен только внутри докеровской сетки по названию контейнера, а наружу ничего не торчит)

2023-05-21 10:56 UTC, m-danya commented on docker-compose.yml
> +        healthcheck:
вот эту штуку добавил чтобы питон не стартанул раньше постгреса и чтобы он не умер от того, что бд недоступна

2023-05-21 10:57 UTC, m-danya commented on docker-compose.yml
> +        healthcheck:
типа конейнер постгреса не будет считаться поднятым, пока он действительно не будет поднятым (а не просто когда запустился)

2023-05-24 21:19 UTC, kobrineli commented on docker-compose.yml
> +        depends_on: [pht-db, pht-redis]
резолвлю)

2023-05-24 21:20 UTC, kobrineli commented on docker-compose.yml
> +        image: postgres:latest
это ты разобрался да, хорош
резолвлю

2023-05-24 21:21 UTC, kobrineli commented on docker-compose.yml
> +        healthcheck:
оки

2023-05-24 21:21 UTC, kobrineli commented on README.md
>  ### Locally
добавил

2023-05-24 21:21 UTC, kobrineli commented on README.md
> +There is an almost ready file called `.env.example` for running via Docker,
поправил

2023-05-24 21:21 UTC, kobrineli commented on Dockerfile
> +CMD poetry env use python3.10 && poetry run python3 src/main.py
поправил))

2023-05-24 21:21 UTC, kobrineli commented on Dockerfile
> +FROM ubuntu:20.04
поправил

2023-05-24 21:21 UTC, kobrineli commented on Dockerfile
> +    apt -y install python3.10 pip && pip install poetry
поправил

2023-05-24 21:41 UTC, merged