Asking about day
m-danya/public-habit-tracker pull request #3
Opened 2023-06-19 21:10 UTC by m-danya

2023-07-03 20:38 UTC, kobrineli requested changes

2023-07-03 20:38 UTC, kobrineli commented on pht/data.py
> +                ).emoji
чет какой-то сложный код с вычислением между понедельником и вс


можно сделать 
```
date = get_nearest_monday(today())
while date != today():
   ...
   date += datetime.timedelta(days=1)
```

2023-07-03 20:38 UTC, kobrineli commented on pht/routes/menu.py
> +async def main_menu_nav(nav: Navigator):
поясни мне потом за этот код пж

2023-07-03 20:38 UTC, kobrineli commented on pht/ask_about_day.py
> +        buttons.append(
можно сразу здесь аппендить `[InlineKeyboardButton(...)]`, тогда ниже не придется повторно итерироваться по кнопкам чтобы каждую в список пихнуть

2023-07-05 15:18 UTC, m-danya commented on pht/routes/menu.py
> +async def main_menu_nav(nav: Navigator):
вкратце -- там просто навигатор проще передать из одной функции в другую, чем дергать `main_menu`, передавая туда какой-то message, по которому с помощью декоратора (некорректно) построится новый навигатор (т.к. message никакого у нас нет при вызове коллбека, мы не можем его пробросить нормально в хендлер, поэтому сиильно проще пробросить готовый навигатор)

2023-07-05 15:22 UTC, kobrineli approved these changes

2023-07-05 15:24 UTC, merged